from datetime import datetime, timezone
from app.database import get_connection


def create_image(image_id, user_id, name, description, file_path, file_size, format_):
    # Inserts a new image record — image_id is pre-generated by the route so the
    # storage directory can be created before the DB write.
    created_at = datetime.now(timezone.utc).isoformat()
    conn = get_connection()
    try:
        conn.execute(
            '''INSERT INTO images
               (id, user_id, name, description, file_path, file_size, format, status, is_public, created_at)
               VALUES (?, ?, ?, ?, ?, ?, ?, 'available', 0, ?)''',
            (image_id, user_id, name, description, file_path, file_size, format_, created_at),
        )
        conn.commit()
        return image_id
    finally:
        conn.close()


def get_image(image_id, user_id=None):
    # user_id scope: returns image only if owned by user OR is public (IDOR prevention)
    conn = get_connection()
    try:
        if user_id:
            row = conn.execute(
                'SELECT * FROM images WHERE id=? AND (user_id=? OR is_public=1)',
                (image_id, user_id),
            ).fetchone()
        else:
            row = conn.execute('SELECT * FROM images WHERE id=?', (image_id,)).fetchone()
        return dict(row) if row else None
    finally:
        conn.close()


def list_images(user_id):
    # Returns all public images + the calling user's own private images
    conn = get_connection()
    try:
        rows = conn.execute(
            '''SELECT * FROM images WHERE is_public=1 OR user_id=?
               ORDER BY created_at DESC''',
            (user_id,),
        ).fetchall()
        return [dict(r) for r in rows]
    finally:
        conn.close()


def delete_image(image_id):
    conn = get_connection()
    try:
        conn.execute('DELETE FROM images WHERE id=?', (image_id,))
        conn.commit()
    finally:
        conn.close()


def set_image_visibility(image_id, is_public):
    conn = get_connection()
    try:
        conn.execute(
            'UPDATE images SET is_public=? WHERE id=?',
            (1 if is_public else 0, image_id),
        )
        conn.commit()
    finally:
        conn.close()


def is_image_in_use(image_id):
    # Checks if any non-terminated instance was launched from this image's file path
    conn = get_connection()
    try:
        row = conn.execute(
            '''SELECT COUNT(*) FROM instances
               WHERE image_path IN (SELECT file_path FROM images WHERE id=?)
               AND status NOT IN ('terminated')''',
            (image_id,),
        ).fetchone()
        return row[0] > 0
    finally:
        conn.close()
